Fix memory leak on orientation change
JoaquimLey/avenging pull request #19
Opened 2016-11-03 23:27 UTC by figengungor

Noticed that when orientation is changed on ListActivity several times, LeakCanary finds a memory leak. Apperantly, RecyclerView in ListFragment leaks ListActivity. When RecyclerView is detached from adapter in onDestroyView(), the memory leak is fixed.

![device-2016-11-04-010557](https://cloud.githubusercontent.com/assets/3411015/19989202/9bb5e0de-a22d-11e6-9ef0-f8d0705a1264.png)

2016-11-04 10:45 UTC, JoaquimLey commented on mobile/src/main/java/com/joaquimley/avenging/ui/list/ListFragment.java
> +        mCharactersRecycler.setAdapter(null);
On a closer inspection, the only reference the adapter has to the fragment is the `ListInteractionListener`. Have you tried to add `mListCharacterAdapter.setListInteractionListener(null);` instead and see if this fixes the leak.

2016-11-04 10:46 UTC, JoaquimLey requested changes
I've left some comments, once again tyvm for your contribution! 😎

2016-11-04 12:07 UTC, figengungor commented on mobile/src/main/java/com/joaquimley/avenging/ui/list/ListFragment.java
> +        mCharactersRecycler.setAdapter(null);
Actually, at first I tried that but it didn't fix the leak. I also added detachment of adapter from RecyclerView, the memory leak went away. Then I removed detaching listener in adapter and the detachment of adapter from RecyclerView by itself was able to solve the leak.

2016-11-04 14:47 UTC, JoaquimLey commented on mobile/src/main/java/com/joaquimley/avenging/ui/list/ListFragment.java
> +        mCharactersRecycler.setAdapter(null);
I've tried it on my side and you're right it does **not** fix the leak.
Although your solution is valid, I was more interested in understanding the **why** so we could actually remove the reference instead of "hot-fixing". If we don't get to the actual reason I'll accept your PR no problem 😉.
- [ ] Find the reference
- [ ] Clear the reference

Once again thanks for your **contribution**

2016-11-04 16:38 UTC, figengungor commented on mobile/src/main/java/com/joaquimley/avenging/ui/list/ListFragment.java
> +        mCharactersRecycler.setAdapter(null);
You are right! I was being lazy stackoverflow copy paster. There is a [stackoverflow post](http://stackoverflow.com/questions/30132643/recyclerview-doesnt-unregister-itself-from-the-adapter-on-orientation-change) describes our problem. If I get it right,  when setRetainInstance(true) is used, onDestroy is not called, RecyclerView doesn't detach its adapter and it leaks the memory.  Also, there is this [answer](http://stackoverflow.com/a/22884377/1463542) about usage of setRetainInstance(true) with UI fragment. So let's keep this open until we figure it out how to handle configuration changes properly.

2016-11-05 14:05 UTC, JoaquimLey commented
Open issue for this **PR** #22

2016-11-14 10:28 UTC, JoaquimLey commented on mobile/src/main/java/com/joaquimley/avenging/ui/list/ListFragment.java
> +        mCharactersRecycler.setAdapter(null);
Just to be sure @figengungor have you got to know a "more elegant" solution? If not I'm going to accept the PR.

2016-11-14 12:51 UTC, figengungor commented on mobile/src/main/java/com/joaquimley/avenging/ui/list/ListFragment.java
> +        mCharactersRecycler.setAdapter(null);
Unfortunately, not yet. You can accept if you want.

2016-11-14 13:56 UTC, JoaquimLey approved these changes

2016-11-14 13:56 UTC, merged

2016-11-14 22:14 UTC, JoaquimLey commented
OK I've accepted it, thanks for the contrib ;)